/** Outfit palettes and short local walks keep the district populated without
 * loading a separate animated character asset for every resident. */
export const NPC_SPECS = [
  { id: 'aoi', name: 'Aoi', role: 'Café owner', style: 'apron', x: -5.4, z: -2, yaw: 1.6, scale: 0.97,
    top: '#fff0dd', bottom: '#614854', accent: '#bf7775', hair: '#543329', hairStyle: 'bun', skin: '#f0bc9b', mission: true,
    greeting: 'Welcome to Hikari! The café is always a good place to begin.' },
  { id: 'ren', name: 'Ren', role: 'Bicycle courier', style: 'hoodie', x: -6, z: 60, yaw: 1.3, scale: 1.04,
    top: '#7cbfaf', bottom: '#32465c', accent: '#f7c965', hair: '#393140', hairStyle: 'short', skin: '#dd9d79', mission: true, bag: true,
    greeting: 'Past the railway, the whole neighborhood opens up. Keep exploring!' },
  { id: 'emi', name: 'Emi', role: 'Market vendor', style: 'vendor', x: 18, z: 85, yaw: -1.5, scale: 0.96,
    top: '#efb960', bottom: '#657c89', accent: '#ba655a', hair: '#703e31', hairStyle: 'bob', skin: '#efb896', mission: true,
    greeting: 'Everything tastes better in the market square. Take your time here.' },
  { id: 'sora', name: 'Sora', role: 'Street photographer', style: 'artist', x: -17, z: 88, yaw: 1.1, scale: 1.01,
    top: '#e8d7bd', bottom: '#6b7390', accent: '#a57cad', hair: '#444057', hairStyle: 'bob', skin: '#eabb9f', mission: true, camera: true,
    greeting: 'The lanterns, the rooftops, the garden… this town has so many good angles.' },
  { id: 'hana', name: 'Hana', role: 'Community gardener', style: 'overalls', x: 18, z: 112, yaw: -1.2, scale: 0.97,
    top: '#e7dcb8', bottom: '#78987c', accent: '#c98a55', hair: '#945e3d', hairStyle: 'ponytail', skin: '#e9b18c', mission: true, hat: 'sun',
    greeting: 'Welcome to the community garden. A little kindness goes a long way.' },
  { id: 'kenji', name: 'Kenji', role: 'Neighborhood guide', style: 'smart', x: -22, z: 108, yaw: 1.4, scale: 1.06,
    top: '#6b8095', bottom: '#363a54', accent: '#d6a276', hair: '#ded2c1', hairStyle: 'short', skin: '#dca580', mission: true, glasses: true,
    greeting: 'I have lived here for years, and I still find something new on every walk.' },
  { id: 'yuki', name: 'Yuki', role: 'High school student', style: 'uniform', x: 6.8, z: -32, yaw: Math.PI, scale: 0.94,
    top: '#ebe5ed', bottom: '#4b577a', accent: '#b96980', hair: '#343047', hairStyle: 'ponytail', skin: '#f0c3a9', bag: true,
    route: [[6.8, -32], [6.8, -26]], greeting: 'The garden beyond the market is my favorite place after school.' },
  { id: 'daichi', name: 'Daichi', role: 'Local musician', style: 'hoodie', x: -6.8, z: 16, yaw: Math.PI, scale: 1.04,
    top: '#b88ea4', bottom: '#4c4967', accent: '#eedbac', hair: '#4b3231', hairStyle: 'short', skin: '#d7a07c', hat: 'cap',
    route: [[-6.8, 16], [-6.8, 22]], greeting: 'I come out here to listen to the sounds of the city.' },
  { id: 'mika', name: 'Mika', role: 'Fashion student', style: 'artist', x: 6, z: 7, yaw: 2.8, scale: 0.98,
    top: '#c98875', bottom: '#e5d6bd', accent: '#84aaa1', hair: '#754856', hairStyle: 'bob', skin: '#e8b494', hat: 'beret', bag: true,
    route: [[6, 7], [6, 10]], greeting: 'You can tell so much about a person from their favorite jacket.' },
  { id: 'haru', name: 'Haru', role: 'Repair shop worker', style: 'overalls', x: 6, z: 48, yaw: 0, scale: 1.08,
    top: '#b96f55', bottom: '#596b87', accent: '#dbb36c', hair: '#3b3232', hairStyle: 'short', skin: '#c98e6b', hat: 'cap',
    route: [[6, 48], [6, 55]], greeting: 'The passage under the railway leads straight to the market.' },
  { id: 'natsumi', name: 'Natsumi', role: 'Evening stroller', style: 'kimono', x: -6, z: 67, yaw: 0.2, scale: 0.98,
    top: '#b982a1', bottom: '#a47598', accent: '#ecd090', hair: '#3d3042', hairStyle: 'bun', skin: '#edbc9f',
    greeting: 'I dressed up for an evening beneath the lanterns.' },
  { id: 'riku', name: 'Riku', role: 'Design student', style: 'uniform', x: -9, z: 79, yaw: 1.8, scale: 1.03,
    top: '#556981', bottom: '#373f58', accent: '#cd9a68', hair: '#6c4631', hairStyle: 'short', skin: '#dfaa83', bag: true,
    route: [[-9, 79], [-16, 79]], greeting: 'There is always someone interesting to meet in this square.' },
  { id: 'akari', name: 'Akari', role: 'Book lover', style: 'smart', x: 10, z: 94, yaw: -1.1, scale: 0.95,
    top: '#be9879', bottom: '#58746d', accent: '#e7d6b8', hair: '#73412e', hairStyle: 'ponytail', skin: '#efbd98', glasses: true,
    route: [[10, 94], [17, 94]], greeting: 'A book, a bench, and a quiet hour. That is a lovely afternoon.' },
  { id: 'tomo', name: 'Tomo', role: 'Flower stall assistant', style: 'vendor', x: -10, z: 98, yaw: 2, scale: 1.02,
    top: '#8bb2b4', bottom: '#697586', accent: '#eed1a2', hair: '#50443e', hairStyle: 'short', skin: '#d29b75',
    greeting: 'Hana looks after the gardens further north. They are beautiful this time of day.' },
  { id: 'kaede', name: 'Kaede', role: 'Garden visitor', style: 'kimono', x: -10, z: 118, yaw: 1, scale: 1,
    top: '#739ca0', bottom: '#668b90', accent: '#e2b081', hair: '#2e3546', hairStyle: 'bun', skin: '#e5b393',
    route: [[-10, 118], [-10, 125]], greeting: 'The little paths here always help me slow down.' },
  { id: 'jun', name: 'Jun', role: 'Weekend painter', style: 'artist', x: 11, z: 128, yaw: -1.8, scale: 1.05,
    top: '#d7b56e', bottom: '#706780', accent: '#749d96', hair: '#655159', hairStyle: 'short', skin: '#dda383', hat: 'beret',
    route: [[11, 128], [17, 128]], greeting: 'The colors change every time I look up from my sketchbook.' },
  // West residential streets and the east canal neighborhood.
  { id: 'kasumi', name: 'Kasumi', role: 'Neighborhood librarian', style: 'smart', x: -6, z: 174, yaw: 0.4, scale: 0.98,
    top: '#a383a0', bottom: '#575f72', accent: '#eee0b9', hair: '#58434e', hairStyle: 'bob', skin: '#dba785', glasses: true,
    route: [[-6, 174], [-6, 181]], greeting: 'The houses west of here have such lovely little gardens. I always take the long way home.' },
  { id: 'teppei', name: 'Teppei', role: 'Canal maintenance worker', style: 'overalls', x: 6, z: 174, yaw: 0.1, scale: 1.07,
    top: '#e1b367', bottom: '#457f89', accent: '#d47856', hair: '#382f33', hairStyle: 'short', skin: '#bb815f', hat: 'cap',
    route: [[6, 174], [6, 180]], greeting: 'Head east to reach the canal. There is plenty of room to walk beside the water.' },
  { id: 'mei', name: 'Mei', role: 'Tea ceremony student', style: 'kimono', x: -6, z: 206, yaw: 0.2, scale: 0.96,
    top: '#bc7977', bottom: '#a2636b', accent: '#e3cfa0', hair: '#453342', hairStyle: 'bun', skin: '#eabc99',
    route: [[-6, 206], [-6, 213]], greeting: 'These quiet residential streets are a lovely change from the market square.' },
  { id: 'fumi', name: 'Fumi', role: 'Canal sketch artist', style: 'artist', x: 6, z: 206, yaw: 0.7, scale: 1.03,
    top: '#90a9af', bottom: '#6d5872', accent: '#daa45e', hair: '#a4774b', hairStyle: 'short', skin: '#d49b76', hat: 'beret', camera: true,
    route: [[6, 206], [6, 214]], greeting: 'I came for the canal reflections and stayed for all the different rooftops.' },
  { id: 'ayame', name: 'Ayame', role: 'School orchestra member', style: 'uniform', x: -86, z: 190, yaw: 0.1, scale: 0.94,
    top: '#e9e3d3', bottom: '#657c78', accent: '#a36274', hair: '#483643', hairStyle: 'ponytail', skin: '#e5b191', bag: true,
    route: [[-86, 190], [-86, 198]], greeting: 'It is a long walk from the old shopping street. I know every corner of this neighborhood now.' },
  { id: 'shun', name: 'Shun', role: 'Weekend cyclist', style: 'hoodie', x: 86, z: 190, yaw: 0.1, scale: 1.06,
    top: '#7183b2', bottom: '#44465d', accent: '#d6a177', hair: '#393647', hairStyle: 'short', skin: '#cd926e', hat: 'cap', bag: true,
    route: [[86, 190], [86, 198]], greeting: 'The canal district is my favorite part of the ride. The streets feel so open over here.' },
  { id: 'chiyo', name: 'Chiyo', role: 'Longtime resident', style: 'kimono', x: -86, z: 220, yaw: 0.1, scale: 0.95,
    top: '#938aad', bottom: '#817293', accent: '#deb178', hair: '#a79c9b', hairStyle: 'bun', skin: '#d0a080', glasses: true,
    route: [[-86, 220], [-86, 227]], greeting: 'I have watched this neighborhood grow for years. The park to the north is a welcome addition.' },
  { id: 'nao', name: 'Nao', role: 'Canalside baker', style: 'apron', x: 86, z: 220, yaw: 0.1, scale: 1.02,
    top: '#edddbd', bottom: '#536f79', accent: '#a26e60', hair: '#795139', hairStyle: 'short', skin: '#e3ad87', hat: 'cap',
    route: [[86, 220], [86, 226]], greeting: 'I am taking a little break by the water before the evening baking starts.' },
  // Civic quarter and the broad northern park; walks stay between crossings.
  { id: 'shiori', name: 'Shiori', role: 'Civic hall volunteer', style: 'smart', x: -6, z: 266, yaw: 0.1, scale: 1,
    top: '#74958b', bottom: '#4f566c', accent: '#e4bf8d', hair: '#634436', hairStyle: 'ponytail', skin: '#eabb97', glasses: true,
    route: [[-6, 266], [-6, 274]], greeting: 'Welcome to the civic quarter. There are open plazas and green spaces all around this end of town.' },
  { id: 'kaito', name: 'Kaito', role: 'Architecture student', style: 'hoodie', x: 6, z: 266, yaw: 0.1, scale: 1.05,
    top: '#c39169', bottom: '#4f6978', accent: '#a2c8b7', hair: '#463338', hairStyle: 'short', skin: '#dca782', bag: true,
    route: [[6, 266], [6, 274]], greeting: 'Look how different the buildings are up here. I am filling a whole sketchbook with them.' },
  { id: 'hinata', name: 'Hinata', role: 'Park groundskeeper', style: 'overalls', x: -86, z: 282, yaw: 0.1, scale: 1,
    top: '#c9b1a1', bottom: '#64847b', accent: '#c49a56', hair: '#694235', hairStyle: 'ponytail', skin: '#d8a27b', hat: 'sun',
    route: [[-86, 282], [-86, 290]], greeting: 'This northern park is much bigger than the old community garden. There is always another patch to look after.' },
  { id: 'asahi', name: 'Asahi', role: 'Public art enthusiast', style: 'artist', x: 86, z: 282, yaw: 0.1, scale: 1.04,
    top: '#b99baa', bottom: '#637580', accent: '#a6ba9b', hair: '#574960', hairStyle: 'bob', skin: '#e1ad8f', hat: 'beret', camera: true,
    route: [[86, 282], [86, 289]], greeting: 'Every plaza has its own character. I am trying to photograph them all before sunset.' },
  { id: 'tomoe', name: 'Tomoe', role: 'Science club member', style: 'uniform', x: -6, z: 302, yaw: 0.1, scale: 0.96,
    top: '#637386', bottom: '#423e59', accent: '#d2a688', hair: '#583e47', hairStyle: 'ponytail', skin: '#eec3a4', glasses: true, bag: true,
    route: [[-6, 302], [-6, 310]], greeting: 'From here you can keep walking north, or take a side street and explore another block.' },
  { id: 'makoto', name: 'Makoto', role: 'Urban planner', style: 'smart', x: 6, z: 302, yaw: 0.1, scale: 1.08,
    top: '#8b849e', bottom: '#3b4d60', accent: '#b6c6b7', hair: '#514246', hairStyle: 'short', skin: '#c88f70', glasses: true,
    route: [[6, 302], [6, 310]], greeting: 'The wide avenues connect the neighborhoods, but my favorite discoveries are along the smaller streets.' },
  { id: 'izumi', name: 'Izumi', role: 'Park flower seller', style: 'vendor', x: -6, z: 340, yaw: 0.1, scale: 0.98,
    top: '#d6a6aa', bottom: '#728b7c', accent: '#efcf8a', hair: '#8b593b', hairStyle: 'bob', skin: '#e9b697', hat: 'sun',
    route: [[-6, 340], [-6, 347]], greeting: 'You made it all the way to the northern park! It is a beautiful place to finish a long walk.' },
  { id: 'tsuki', name: 'Tsuki', role: 'Travel illustrator', style: 'artist', x: 6, z: 340, yaw: 0.1, scale: 1,
    top: '#dabd8e', bottom: '#79718f', accent: '#a2697f', hair: '#483b56', hairStyle: 'bob', skin: '#dba787', hat: 'beret', bag: true,
    route: [[6, 340], [6, 348]], greeting: 'I started at the little café and kept going. There is enough of this town to fill an entire travel journal.' },
];
